version: "2.1"

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
  proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DIR}/app-data/proxy/certs:/etc/nginx/certs:ro
      - ${DIR}/app-data/proxy/vhostd:/etc/nginx/vhost.d
      - ${DIR}/app-data/proxy/html:/usr/share/nginx/html
      - ${DIR}/app-data/proxy/nginx-conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  ssl:
    image: nginxproxy/acme-companion:latest
    restart: always
    container_name: ssl
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: ${EMAIL}
    volumes:
      - ${DIR}/app-data/proxy/certs:/etc/nginx/certs
      - ${DIR}/app-data/proxy/vhostd:/etc/nginx/vhost.d
      - ${DIR}/app-data/proxy/html:/usr/share/nginx/html
      - ${DIR}/app-data/proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: postgres:11
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ${DIR}/app-data/postgres_data:/var/lib/postgresql/data
  terrastories:
    image: communityfirst/terrastories
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ${DIR}/app-data/terrastories/bundler:/usr/local/bundle
      - ${DIR}/app-data/terrastories/data:/api
      - ${DIR}/app-data/terrastories/media:/media
      - ${DIR}/app-data/terrastories/import:/api/import/media