version: "2.1"
volumes:
  postgres_data:
  bundler:
  terrastories-data:
  terrastories-media:
  terrastories-import:
  certs:
  vhost:
  html:
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  ssl:
    image: nginxproxy/acme-companion:latest
    restart: always
    container_name: ssl
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: ${EMAIL}
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: postgres:11
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  terrastories:
    image: communityfirst/terrastories
    env_file:
    - ./.env
    depends_on:
      - db
    volumes:
      - bundler:/usr/local/bundle
      - terrastories-data:/api
      - terrastories-media:/media
      - terrastories-import:/api/import/media
